#deployment and service for orientdb   with persistent volume 
#after run this you can run python-orientdb to run the flask api to interact with the db

#Service definition to expose the db
apiVersion: v1
kind: Service
metadata:
  name: orientdb-service
  labels: 
    app: orientdb
spec:
  selector:
    app: orientdb
  ports:
  - protocol: "TCP"
    name: ui
    port: 2424
    targetPort: 2424
  - protocol: "TCP"
    name: endpoints
    port: 2480
    targetPort: 2480
  type: LoadBalancer
   
---
#deployment definition
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orientdb
spec:
  selector:
    matchLabels:
      app: orientdb
  replicas: 1
  template:
    metadata:
      labels:
        app: orientdb
    spec:
      containers:
      - name: orientdb
        image: library/orientdb:3.0.30
        command: ["/orientdb/bin/server.sh"]
        env:
        - name: ORIENTDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: orientdb-pass
              key: password.txt
        -  name: ORIENTDB_NODE_NAME
           value: server1
        ports:
        - containerPort: 2424
          name: port-binary
        - containerPort: 2480
          name: port-http
        volumeMounts:
        - mountPath: /orientdb/databases
          name: orientdb-data
          subPath: databases
        - mountPath: /orientdb/backup
          name: orientdb-data
          subPath: backup
      volumes:
      - name: orientdb-data
        persistentVolumeClaim:
          claimName: orientdb-pv-claim-alone
---
#persistent volume claims
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: orientdb-pv-claim-alone
spec:
  volumeName: pv-volume-alone
  storageClassName: local-storage
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
#persistent volume in retain mode
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "pv-volume-alone"
spec:
  capacity:
    storage: "10Gi"
  accessModes:
    - "ReadWriteMany"
  hostPath:
    path: /data
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
