#deployment and service for orientdb instance  with persistent volume defined from volume-claim.yml
apiVersion: v1
kind: Service
metadata:
  name: orientdb-service
  labels: 
    app: orientdb-d
spec:
  selector:
    app: orientdb-d
  ports:
  - protocol: "TCP"
    name: ui
    port: 2424
    targetPort: 2424
  - protocol: "TCP"
    name: endpoints
    port: 2480
    targetPort: 2480
  type: LoadBalancer
   
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orientdb-d
spec:
  selector:
    matchLabels:
      app: orientdb-d
  replicas: 1
  template:
    metadata:
      labels:
        app: orientdb-d
    spec:
      containers:
      - name: orientdb-d
        image: library/orientdb:3.0.30
        command: ["/orientdb/bin/dserver.sh"]
        env:
        - name: ORIENTDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: orientdb-pass
              key: password.txt
        ports:
        - containerPort: 2424
          name: port-binary
        - containerPort: 2480
          name: port-http
        volumeMounts:
        - mountPath: /orientdb/databases
          name: orientdb-data
          subPath: databases
        - mountPath: /orientdb/backup
          name: orientdb-data
          subPath: backup
      volumes:
      - name: orientdb-data
        persistentVolumeClaim:
          claimName: orientdb-pv-claim-2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orientdb-d2
spec:
  selector:
    matchLabels:
      app: orientdb-d
  replicas: 1
  template:
    metadata:
      labels:
        app: orientdb-d
    spec:
      containers:
      - name: orientdb-d
        image: library/orientdb:3.0.30
        command: ["/orientdb/bin/server.sh"]
        env:
        - name: ORIENTDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: orientdb-pass
              key: password.txt
        -  name: ORIENTDB_NODE_NAME
           value: server1
        ports:
        - containerPort: 2424
          name: port-binary
        - containerPort: 2480
          name: port-http
        volumeMounts:
        - mountPath: /orientdb/databases
          name: orientdb-data
          subPath: databases
        - mountPath: /orientdb/backup
          name: orientdb-data
          subPath: backup
      volumes:
      - name: orientdb-data
        persistentVolumeClaim:
          claimName: orientdb-pv-claim-1
