#deployment and service for orientdb in distributed mode instances  with persistent volume 
#before run this make sure to run persistent volume then volume claims and volume claims2
#after run this you can run python-orientdb to run the flask api to interact with the db


apiVersion: v1
kind: Service
metadata:
  name: orientdb-service
  labels: 
    app: orientdb-d
spec:
  selector:
    app: orientdb-d
  ports:
  - protocol: "TCP"
    name: ui
    port: 2424
    targetPort: 2424
  - protocol: "TCP"
    name: endpoints
    port: 2480
    targetPort: 2480
  type: LoadBalancer
   
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orientdb-d
spec:
  selector:
    matchLabels:
      app: orientdb-d
  replicas: 1
  template:
    metadata:
      labels:
        app: orientdb-d
    spec:
      containers:
      - name: orientdb-d
        image: library/orientdb:3.0.30
        command: ["/bin/sh","-c", "cp /config/customConfig/* /orientdb/config/ ; /orientdb/bin/dserver.sh " ]
        env:
        - name: ORIENTDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: orientdb-pass
              key: password.txt
        ports:
        - containerPort: 2424
          name: port-binary
        - containerPort: 2480
          name: port-http
        volumeMounts:
        - mountPath: /orientdb/databases
          name: orientdb-data
          subPath: databases
        - mountPath: /orientdb/backup
          name: orientdb-data
          subPath: backup
        - name: config
          mountPath: /config
        # These containers are run during pod initialization to get config files from github
      initContainers:
      - name: install
        image: alpine/git
        command: ["/bin/sh","-c"]
        args: [git clone https://github.com/orland1to/orientdbConfig.git /config/customConfig]
        volumeMounts:
        - name: config
          mountPath: /config
      volumes:
      - name: config
        emptyDir: {}
      - name: orientdb-data
        persistentVolumeClaim:
          claimName: orientdb-pv-claim-1
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: orientdb-pv-claim-1
spec:
  volumeName: pv-volume
  storageClassName: local-storage
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "pv-volume"
spec:
  capacity:
    storage: "10Gi"
  accessModes:
    - "ReadWriteMany"
  hostPath:
    path: /data
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage